LOGIN_SESSION_ID = 'user_id'

# 客户类别
CLIENT_TYPE_CUSTOMER = 10
CLIENT_TYPE_CHANNEL = 20
CLIENT_TYPE_CHOICES = (
    (CLIENT_TYPE_CUSTOMER, '直客'),
    (CLIENT_TYPE_CHANNEL, '渠道'),
)

# 开单/退款
INVOICE_TYPES_ORDER = 10
INVOICE_TYPES_REFUND = 20
INVOICE_TYPES_CHOICES = (
    (INVOICE_TYPES_ORDER, '开单'),
    (INVOICE_TYPES_REFUND, '退款'),
)
